<a href="https://colab.research.google.com/github/AnhVietPham/Machine-Learning/blob/main/Expected_Value%2C_Variance%2C_and_Covariance_with_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Expected Value**

In [4]:

from numpy import array
from numpy import mean
from numpy import var
M = array([[1,2,3,4,5,6],[1,2,3,4,5,6]])
print(M)
col_mean = mean(M, axis=0)
print(col_mean)
row_mean = mean(M, axis=1)
print(row_mean)

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]
[1. 2. 3. 4. 5. 6.]
[3.5 3.5]


**Variance**


In [7]:
v = array([1,2,3,4,5,6])
print(v)
result = var(v, ddof = 1)
print(result)

[1 2 3 4 5 6]
3.5


In [10]:
M = array([[1,2,3,4,5,6],[1,2,3,4,5,6]])
print(M)
col_mean = var(M, ddof = 1, axis=0)
print(col_mean)
row_mean = var(M, ddof=1, axis=1)
print(row_mean)

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]
[0. 0. 0. 0. 0. 0.]
[3.5 3.5]


**Standard Deviation**

In [13]:
from numpy import std
M1 = array([[1,2,3,4,5,6],[1,2,3,4,5,6]])
print(M1)
col_mean_std = std(M1, ddof = 1, axis = 0)
print(col_mean_std)
row_mean_std = std(M1, ddof = 1, axis = 1)
print(row_mean_std)

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]
[0. 0. 0. 0. 0. 0.]
[1.87082869 1.87082869]
