<a href="https://colab.research.google.com/github/AnhVietPham/Machine-Learning/blob/main/Pytorch_Intro_To_CNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Pytorch [Basics] — Intro to CNN**
https://towardsdatascience.com/pytorch-basics-how-to-train-your-neural-net-intro-to-cnn-26a14c2ea29

In [1]:
import numpy as np

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader

In [44]:
input_1D = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype = torch.float)

input_2D = torch.tensor([
                         [1, 2, 3, 4, 5], 
                         [6, 7, 8, 9, 10]
                         ], 
                        dtype = torch.float)

input_2D_image = torch.tensor([[
                                [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 
                                [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 
                                [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]], 
                               [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 
                                [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 
                                [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]], 
                               [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 
                                [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 
                                [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]]], 
                              dtype = torch.float)

print("===============Output================")
print(f"input_1D size: {input_1D.shape}")
print(input_1D)
print(f"input_2D size: {input_2D.shape}")
print(input_2D)
print(f"input_2D_image size: {input_2D_image.shape}")
print(input_2D_image)

===============Output================
input_1D size: torch.Size([10])
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
input_2D size: torch.Size([2, 5])
tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])
input_2D_image size: torch.Size([3, 3, 10])
tensor([[[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]],

        [[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]],

        [[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]])


# **1D Convolution**

# **Conv1d - Input 1d**

In [36]:
input_1D = input_1D.unsqueeze(0).unsqueeze(0)
print(input_1D.shape)
input_1D

torch.Size([1, 1, 10])


tensor([[[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]])

In [29]:
cnn1d_1 = nn.Conv1d(in_channels=1, out_channels=1, kernel_size=3, stride=1)

print("cnn1d_1: \n")
print(cnn1d_1(input_1D).shape, "\n")
print(cnn1d_1(input_1D))

cnn1d_1: 

torch.Size([1, 1, 8]) 

tensor([[[-0.2565, -0.1887, -0.1209, -0.0531,  0.0147,  0.0825,  0.1504,
           0.2182]]], grad_fn=<SqueezeBackward1>)


In [37]:
cnn1d_2 = nn.Conv1d(in_channels=1, out_channels=1, kernel_size=3, stride=2)
print("cnn1d_2: \n")
print(cnn1d_2(input_1D).shape, "\n")
print(cnn1d_2(input_1D))

cnn1d_2: 

torch.Size([1, 1, 4]) 

tensor([[[0.8065, 1.4384, 2.0703, 2.7022]]], grad_fn=<SqueezeBackward1>)


In [38]:
cnn1d_3 = nn.Conv1d(in_channels=1, out_channels=1, kernel_size=2, stride=1)
print("cnn1d_2: \n")
print(cnn1d_3(input_1D).shape, "\n")
print(cnn1d_3(input_1D))

cnn1d_2: 

torch.Size([1, 1, 9]) 

tensor([[[-1.0938, -2.0468, -2.9997, -3.9527, -4.9057, -5.8586, -6.8116,
          -7.7645, -8.7175]]], grad_fn=<SqueezeBackward1>)


In [41]:
cnn1d_4 = nn.Conv1d(in_channels=1, out_channels=5, kernel_size=3, stride=1)
print("cnn1d_2: \n")
print(cnn1d_4(input_1D).shape, "\n")
print(cnn1d_4(input_1D))

cnn1d_2: 

torch.Size([1, 5, 8]) 

tensor([[[ 2.8726,  4.3583,  5.8440,  7.3297,  8.8154, 10.3011, 11.7867,
          13.2724],
         [-0.0860, -0.3899, -0.6938, -0.9976, -1.3015, -1.6053, -1.9092,
          -2.2130],
         [-0.9040, -0.8340, -0.7640, -0.6940, -0.6240, -0.5540, -0.4840,
          -0.4139],
         [ 1.3774,  2.4401,  3.5027,  4.5654,  5.6281,  6.6908,  7.7535,
           8.8162],
         [ 0.8838,  1.5763,  2.2689,  2.9615,  3.6540,  4.3466,  5.0392,
           5.7317]]], grad_fn=<SqueezeBackward1>)


# **Conv1d - Input 2d**

In [45]:
input_2D = input_2D.unsqueeze(0)
print(input_2D)
print(input_2D.shape)

tensor([[[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]])
torch.Size([1, 2, 5])


In [46]:
cnn1d_5 = nn.Conv1d(in_channels=2, out_channels=1, kernel_size=3, stride=1)
print("cnn1d_5: \n")
print(cnn1d_5(input_2D).shape, "\n")
print(cnn1d_5(input_2D))

cnn1d_5: 

torch.Size([1, 1, 3]) 

tensor([[[-2.2745, -2.6462, -3.0180]]], grad_fn=<SqueezeBackward1>)


In [48]:
cnn1d_6 = nn.Conv1d(in_channels=2, out_channels=1, kernel_size=3, stride=2)
print("cnn1d_6: \n")
print(cnn1d_6(input_2D).shape, "\n")
print(cnn1d_6(input_2D))

cnn1d_6: 

torch.Size([1, 1, 2]) 

tensor([[[-1.2960, -1.7628]]], grad_fn=<SqueezeBackward1>)


In [49]:
cnn1d_7 = nn.Conv1d(in_channels=2, out_channels=1, kernel_size=2, stride=1)
print("cnn1d_7: \n")
print(cnn1d_7(input_2D).shape, "\n")
print(cnn1d_7(input_2D))

cnn1d_7: 

torch.Size([1, 1, 4]) 

tensor([[[0.5183, 0.8004, 1.0826, 1.3647]]], grad_fn=<SqueezeBackward1>)


In [50]:
cnn1d_8 = nn.Conv1d(in_channels=2, out_channels=5, kernel_size=3, stride=1)
print("cnn1d_8: \n")
print(cnn1d_8(input_2D).shape, "\n")
print(cnn1d_8(input_2D))

cnn1d_8: 

torch.Size([1, 5, 3]) 

tensor([[[-0.1121,  0.1713,  0.4546],
         [ 0.2283,  0.2956,  0.3628],
         [ 3.9839,  4.1527,  4.3216],
         [ 0.7778,  1.1358,  1.4938],
         [-0.7759, -0.8898, -1.0038]]], grad_fn=<SqueezeBackward1>)


# **2D Convolution**

In [51]:
input_2D_image = input_2D_image.unsqueeze(0)
input_2D_image.shape

torch.Size([1, 3, 3, 10])

In [53]:
cnn2d_1 = nn.Conv2d(in_channels=3, out_channels=1, kernel_size=3, stride=1)

print("cnn2d_1: \n")
print(cnn2d_1(input_2D_image).shape, "\n")
print(cnn2d_1(input_2D_image))

cnn2d_1: 

torch.Size([1, 1, 1, 8]) 

tensor([[[[0.3402, 0.8128, 1.2855, 1.7581, 2.2308, 2.7034, 3.1761, 3.6487]]]],
       grad_fn=<ThnnConv2DBackward>)


In [54]:
cnn2d_1 = nn.Conv2d(in_channels=3, out_channels=1, kernel_size=3, stride=2)

print("cnn2d_1: \n")
print(cnn2d_1(input_2D_image).shape, "\n")
print(cnn2d_1(input_2D_image))

cnn2d_1: 

torch.Size([1, 1, 1, 4]) 

tensor([[[[0.4484, 1.1495, 1.8507, 2.5518]]]], grad_fn=<ThnnConv2DBackward>)
